# We do not use sudo
sudo: false
branches:
  only:
    master

# Python versions for matrix
language: python
python:
  - "3.5-dev"

env:
 - TOX_ENV=flake8
 - TOX_ENV=coverage-no-report
 - TOX_ENV=doc
install:
 - pip install tox coveralls
script:
 - tox -e $TOX_ENV

after_success:
 - coveralls
